name: tests
on: [push]

jobs:
  exec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.x', 'pypy-2.7', 'pypy-3.7', 'pypy-3.8' ]
    steps:
      - uses: actions/checkout@v3
      - name: Installation python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Installation Python
        uses: py-actions/py-dependency-install@v3
        with:
          path: "./requirements.txt"
      - name: Lancer Application
        run: pytest
      - name: Create Issue on Failed workflow
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Action workflow failed.
          body: |
            Workflow name - `${{ github.workflow }}`
            Job -           `${{ github.job }}`
            status -        `${{ job.status }}`
        